### ISSUE TITLE
Cipher and Cipher suites: new resource proposal

### ISSUE THREAD

**Issue by fullenw1** [dsccommunity/xSystemSecurity#27]
### Description
Currently we are managing **Protocols**, **Ciphers** and **Cipher Suites** through a lot of registry entries which is a tedious task.
With DSC resources it would a lot easier for us.

### Proposed properties
**ProtocolsToDisable**: SSL2.0  | SSL3.0 | TLS1.0 | TLS1.1

**CiphersToDisable**: RC4 40/128 | RC4 56/128 | RC4 128/128 | Triple DES 168

**CypherSuitesToDisable**: TLS_RSA_WITH_AES_256_GCM_SHA384 | TLS_RSA_WITH_AES_128_GCM_SHA256 | TLS_RSA_WITH_AES_256_CBC_SHA256 | TLS_RSA_WITH_AES_128_CBC_SHA256 | TLS_RSA_WITH_AES_256_CBC_SHA | TLS_RSA_WITH_AES_128_CBC_SHA

### Special considerations or limitations
A good explanation: [https://blogs.technet.microsoft.com/askds/2015/12/08/speaking-in-ciphers-and-other-enigmatic-tonguesupdate/](https://blogs.technet.microsoft.com/askds/2015/12/08/speaking-in-ciphers-and-other-enigmatic-tonguesupdate/)

**Comment by johlju** [comment]
Sounds like a good addition.

**Comment by johlju** [comment]
@fullenw1 are you interested in creating a resource for this?

**Comment by fullenw1** [comment]
@johlju 

This is probably the way to go for me, a real challenge and opportunity to improve my skills.

However, I will need a lot of help because I am new to the process (all steps needed before a release) and also my Pester knowledge is currently about 2 on scale of 10...

Who would be able to "coach" me and assist me in this task?

**Comment by johlju** [comment]
Awesome! It is perfectly fine if you need help, we all have been there, to get you to the point that you have sent in a pull request. 🙂 

Suggested reading (unless you already know this):
Please read through this https://dsccommunity.org/guidelines/getting-started/ and then continue with https://dsccommunity.org/guidelines/contributing/#understand-the-coding-workflow then there are other sections in the last link that will be of interest to you. 🙂 
In regards to pester you can look at https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithPester.md (we have not had the time to move that guide to the DSC Community yet). Not sure if that guide is to basic, maybe you already know that since you have used Pester before.

If you need help you can find the community talking here https://dsccommunity.org/community/contact/, and you can also tag me and others here on GitHub as needed. But most of us is in the Slack channel, and is often easier to speak there. 🙂

**Comment by johlju** [comment]
@fullenw1 before you start though, I found this. Double-check if the functionality exist here https://www.powershellgallery.com/packages/SchannelPolicyDsc/1.0.0 (repo here https://github.com/citadelgroup/SchannelPolicyDsc), or if that can be extended to match your needs. No need to duplicate the work. 🙂

**Comment by johlju** [comment]
There seems also to be one here https://www.powershellgallery.com/packages/SChannelDsc/1.0.0.0 (repo here https://github.com/Microsoft/SChannelDsc)

**Comment by fullenw1** [comment]
@johlju 

Yes you are right, the SChannelDsc is already doing all this stuff.
No need for a new resource :)

However, it would be great if the SChannellDsc module could merge into the xSystemSecurity module.
Because when somebody who has never done this task manually wants to disable SSL 3.0 or another cipher object, and has a look at all the available modules, the first one he/she will look at is xSystemSecurity because the name is a kind of evidence.
SChannel is a word which is only know by people who tried to set those values manually in the registry.

**Comment by johlju** [comment]
It would be great to add those resource to the DSC Community. It would be better if we created a new repo in DSC community that is named SystemSecurityDsc and move the resources there. As an alternative the resources could also be added to ComputerManagementDsc. But that is up to the maintainer of the SChannelDsc repo. Please raise an issue in that repo asking the maintainer if he is interested in that.

**Comment by johlju** [comment]
The maintainer can find us on Slack https://dsccommunity.org/community/contact/

**Comment by johlju** [comment]
Closing this issue at this time. Thank you for raising this! 😃
